# gunakan API versi 1
apiVersion: v1

# tentukan jenis object = Service
kind: Service

# metadata
metadata:
  # nama = backend
  name: karsajobs-microservices
  #labels
  labels:
    app: karsajobs
    tier: backend

# tentukan spesifikasi
spec:
  # tentukan port dari service
  ports:
  - name: default
    port: 8080
    protocol: TCP
  # tentukan selector
  selector:
    app: karsajobs
    tier: backend
  type: NodePort